services:
  postgres:
    image: '${PRIVATE_REPOSITORY}postgres:${POSTGRES_VERSION}'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - './pg_data:/var/lib/postgresql/data' # . (Titik) sama aja kaya $PWD
    ports:
      - '5432:5432'

  flyway:
    image: '${PRIVATE_REPOSITORY}redgate/flyway'
    command: -url=jdbc:postgresql://postgres:5432/hr -user=hr -password=hr -connectRetries=60 migrate info
    profiles:
      - migrate
    volumes:
      - './db/migration:/flyway/sql'
    depends_on:
      - postgres

  pgadmin4:
    image: '${PRIVATE_REPOSITORY}dpage/pgadmin4'
    profiles:
      - debug
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@example.com'
      - 'PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '55432:80'
#    volumes:
#      - './pg_admin_data:/var/lib/pgadmin'
    depends_on:
      - postgres
volumes:
  pg_data:
#  pg_admin_data: